Traceback (most recent call last):
  File "/scratch/hzenati/double-debiased-machine-learning-mediation-continuous-treatments/experiment_coverage_uniform.py", line 219, in <module>
    experiment(args)
  File "/scratch/hzenati/double-debiased-machine-learning-mediation-continuous-treatments/experiment_coverage_uniform.py", line 126, in experiment
    causal_data = causal_env.generate_causal_data(data_settings, random_state=param_settings['random_seed'])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/hzenati/double-debiased-machine-learning-mediation-continuous-treatments/data/uniform.py", line 63, in generate_causal_data
    X = rng.uniform(-1.5, 1.5, size=(n_samples,1))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/mtrand.pyx", line 1158, in numpy.random.mtrand.RandomState.uniform
  File "_common.pyx", line 636, in numpy.random._common.cont
TypeError: 'NoneType' object cannot be interpreted as an integer
